name: NestJs Pipeline
on:
  pull_request:
    branches:
      - master
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 14
      - name: Install Dependencies
        run: npm install
      - name: Install TypeScript
        run: npm install --save-dev typescript
      - name: Install MongoDB
        run: npm install --save @nestjs/mongoose mongoose
      - name: Install validators
        run: npm install class-validator --save
      - name: Install validator transformer
        run: npm install class-transformer --save
      - name: Install mapped-types
        run: npm i @nestjs/mapped-types --save
      - name: Compile TypeScript
        run: npm run start
      - name: Run Tests
        run: npm run test
      - name: Build Application
        run: npm run build
